### ISSUE TITLE
KeyError: 'description' in repos command

### ISSUE THREAD

**Issue by raydouglass** [amalfra/docker-hub#18]
Suddenly just started to get this error from version 3.0.0 of the library: 
```
$ docker-hub repos -o rapidsai
Traceback (most recent call last):
  File "/Users/rdouglass/miniforge3/envs/dockerhubtest/bin/docker-hub", line 8, in <module>
    sys.exit(main())
  File "/Users/rdouglass/miniforge3/envs/dockerhubtest/lib/python3.9/site-packages/docker_hub/cli.py", line 74, in main
    command.run(docker_hub_client, args)
  File "/Users/rdouglass/miniforge3/envs/dockerhubtest/lib/python3.9/site-packages/docker_hub/commands/repos.py", line 23, in run
    rows.append([repo['name'], repo['description'],
KeyError: 'description'
```

It looks like `description` isn't provided by the API anymore.

**Comment by amalfra** [comment]
@raydouglass Thanks for reporting the bug. This will be fixed in the upcoming release that's going to happen soon.

**Comment by amalfra** [comment]
@raydouglass Latest release of [V4.0](https://github.com/amalfra/docker-hub/releases/tag/4.0.0 ) fixes this. As API no longer returns description instead of that "Repository Type" will be shown.
